/* PSPP - a program for statistical analysis.
   Copyright (C) 2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>. */

#ifndef QQ_H
#define QQ_H

#include "libpspp/str.h"
#include "libpspp/hmap.h"
#include "data/value.h"
#include "output/chart-item.h"


struct qq
  {
    struct chart_item chart_item;
  };


struct variable;
struct freq;

struct qq *qq_create (const struct variable **, int n_vars,
				    const char *ylabel, bool percent,
                                    struct freq *const *, int n_cats);

/* This boilerplate for qq, a subclass of chart_item, was
   autogenerated by mk-class-boilerplate. */

#include <assert.h>
#include "libpspp/cast.h"

extern const struct chart_item_class qq_class;

/* Returns true if SUPER is a qq, otherwise false. */
static inline bool
is_qq (const struct chart_item *super)
{
  return super->class == &qq_class;
}

/* Returns SUPER converted to qq.  SUPER must be a qq, as
   reported by is_qq. */
static inline struct qq *
to_qq (const struct chart_item *super)
{
  assert (is_qq (super));
  return UP_CAST (super, struct qq, chart_item);
}

/* Returns INSTANCE converted to chart_item. */
static inline struct chart_item *
qq_super (const struct qq *instance)
{
  return CONST_CAST (struct chart_item *, &instance->chart_item);
}

/* Increments INSTANCE's reference count and returns INSTANCE. */
static inline struct qq *
qq_ref (const struct qq *instance)
{
  return to_qq (chart_item_ref (&instance->chart_item));
}

/* Decrements INSTANCE's reference count, then destroys INSTANCE if
   the reference count is now zero. */
static inline void
qq_unref (struct qq *instance)
{
  chart_item_unref (&instance->chart_item);
}

/* Returns true if INSTANCE's reference count is greater than 1,
   false otherwise. */
static inline bool
qq_is_shared (const struct qq *instance)
{
  return chart_item_is_shared (&instance->chart_item);
}

static inline void
qq_submit (struct qq *instance)
{
  chart_item_submit (&instance->chart_item);
}

#endif /* output/charts/qq.h */
