/* 	-*- mode: c; buffer-read-only: t -*-
   Generated by src/libpspp/automake.mk --- Do not edit.

   The following line is for the benefit of the perl module
$VERSION='0.10.4';
*/
#include "version.h"
const char bare_version[] = "0.10.4";
const char version[] = "GNU pspp 0.10.4";
const char announced_version[] = "GNU pspp 0.10.4";
const char host_system[] = "x86_64-pc-linux-gnu";
const char build_system[] = "x86_64-pc-linux-gnu";
const char locale_dir[] = "/usr/local/share/locale";
const char examples_dir[] = "/usr/local/share/pspp/examples";
const char *const authors[] = {
  "We wish to thank current active contributors to PSPP:",
  "",
  "* Ben Pfaff wrote the initial program and manual, which comprises the",
  "majority of the current code. Ben continues to contribute and ",
  "most of the core libraries which ensure that PSPP runs with optimal",
  "speed are his work.",
  "",
  "* John Darrington wrote the initial version of the graphical user interface,",
  "and many of the statistical procedures.  John also implemented support for",
  "long variable names, PostgreSQL and Gnumeric and made numerous",
  "revisions to other modules.",
  "",
  "* Jason Stover contributed statistical and numerical functionality,",
  "including lib/gslextras and the linear regression features. Jason ",
  "is also an important contributor to GSL, which is used by PSPP. ",
  "",
  "* Mehmet Hakan Satman provided the initial implementation of the QUICK CLUSTER command.",
  "  Alan Mead and others contributed later improvements including the cluster membership subcommands.",
  "",
  "* Friedrich Beckmann wrote the GRAPH command.",
  "",
  "We also thank past contributors:",
  "",
  "* John Williams wrote an initial draft of the T-TEST procedure.",
  "",
  "* Michael Kiefte contributed bug fixes and other enhancements.",
  "",
  "* Patrick Kobly contributed bug fixes and other enhancements.",
  "",
  "* Rob van Son wrote the original version of the routine for",
  "  calculation of the significance of the Wilcoxon matched pairs signed",
  "  rank statistic used by the NPAR TEST command.",
  "",
0 };
